export const DataDesign = [
  // 1단계 문제
  {},
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "B",
    Point: 20,
    Choice: ["A", "B"],
    src: "/img/1.svg",
    isImgExist: true,
    Desc: "“Placeholder”는 입력칸 안에 먼저 보여주는 예시문이에요. 사용자가 입력을 시작하면 보이지 않기 때문에, 무엇을 입력해야 하는지 항상 보이게 하는게 좋아요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "B",
    Point: 10,
    Choice: ["A", "B"],
    src: "/img/2.svg",
    isImgExist: true,
    Desc: "“행간”은 문장과 문장 사이의 간격을 의미해요. 한 문단을 읽는데 있어서 중요한 요소이기에, 문장 간에 충분한 간격을 벌려주는 게 좋아요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "B",
    Point: 20,
    Choice: ["A", "B"],
    src: "/img/3.svg",
    isImgExist: true,
    Desc: "“들여쓰기”는 본문을 쓰고 읽는데 있어서 중요한 요소에요. 각 주제를 명확하게 구분하고 독자가 글을 쉽게 읽을 수 있도록 하기 위해, 본문의 내용을 들여쓰기 하는게 중요해요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "B",
    Point: 20,
    Choice: ["A", "B"],
    src: "/img/4.svg",
    isImgExist: true,
    Desc: "보통 부제목보다는 주제목에 더 중요한 내용이 들어가는 경우가 많아요. 그렇기 때문에, 부제목보다는 주제목을 더 강조하는 게 좋아요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "A",
    Point: 30,
    Choice: ["A", "B"],
    src: "/img/5.svg",
    isImgExist: true,
    Desc: "“드롭다운 메뉴”는 선택할 요소를 차례대로 보여주는 메뉴에요. 만약 선택할 수 있는 옵션이 많다면 사용하기에 좋지만, 요소가 적다면 리스트 형태가 더 적합해요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "A",
    Point: 30,
    Choice: ["A", "B"],
    src: "/img/6.svg",
    isImgExist: true,
    Desc: "우리가 무언가 선택할 때는 이전에 자주 선택한 것을 다시 선택하는 경향이 있어요. 때문에, 사람들이 자주 선택하는 옵션은 미리  활성화 시켜주는 게 좋아요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "B",
    Point: 20,
    Choice: ["A", "B"],
    src: "/img/7.svg",
    isImgExist: true,
    Desc: "“텍스트 버튼”은 일반 텍스트와의 구별을 위해 일반 텍스트와는 다른 계열의 색상을 사용하는게 좋아요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "A",
    Point: 30,
    Choice: ["A", "B"],
    src: "/img/8.svg",
    isImgExist: true,
    Desc: "버튼의 내용을 “네 / 아니요”로 구성하게 되면 버튼을 눌렀을 때 어떤 걸 할 수 있는지 모를 수 있어요. 그렇기에 버튼을 눌렀을 때 어떤 것을 할 수 있는지를 알려주는 게 좋아요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "A",
    Point: 10,
    Choice: ["A", "B"],
    src: "/img/9.svg",
    isImgExist: true,
    Desc: "버튼의 색깔은 그 버튼이 어떤 의미를 가지고 있는 지를 나타내기도 해요. 그렇기 때문에 버튼의 속성에 따라 색상을 다르게 하는게 좋아요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "B",
    Point: 20,
    Choice: ["A", "B"],
    src: "/img/10.svg",
    isImgExist: true,
    Desc: "만약 텍스트와 배경의 색이 크게 차이가 나지 않으면 내용이 제대로 보이지 않을 수 있어요. 텍스트와 배경 색깔에 차이를 주는게 좋아요.",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "A",
    Point: 30,
    Choice: ["A", "B"],
    src: "/img/11.svg",
    isImgExist: true,
    Desc: "과한 윤곽선은 디자인이 연결되는 느낌을 사라지게 해요. 윤곽선이 많으면 시각적으로 눈에 불편함을 주기도 하니, 최대한 자연스럽게 넣어주세요!",
    trueisSubject: false,
  },
  {
    Q: "어떤 디자인이 더 좋은 디자인일까요?",
    Ans: "B",
    Point: 30,
    Choice: ["A", "B"],
    src: "/img/12.svg",
    isImgExist: true,
    Desc: "검정과 하양의 대비는 극과 극이에요. 대비가 심한 만큼 가독성은 좋아지지만, 눈의 피로도 역시 유발하게 돼요! 사용자의 눈 피로도를 줄이기 위해 대비를 줄이는 것이 좋아요.",
    trueisSubject: false,
  },
];
